### ISSUE TITLE
Need option to suppress all color coding in output

### ISSUE THREAD

**Issue by dkerr64** [troglobit/netcalc#10]
netcalc needs a way to output without any color coding.  The control characters inserted before IPv6 addresses make it impossible to parse the strings output within another script (e.g. bash).  So, for example, you cannot rely on substring:position because there are hidden control characters imbedded into the front of the ip address string.

**Comment by abelbeck** [comment]
@troglobit read your mind :-) and committed a -c option to do that. 390def60 a few hours ago.

**Comment by troglobit** [comment]
Yup

**Comment by dkerr64** [comment]
thanks, I'll give it a try

**Comment by troglobit** [comment]
Just FYI, we'll be changing the option syntax shortly.
