### ISSUE TITLE
2.1 release tarball missing doc_DATA files

### ISSUE THREAD

**Issue by abelbeck** [troglobit/netcalc#14]
The README.md LICENSE ChangeLog.md files are missing from the release tarball.

As such ```make``` fails with:
```
make[2]: *** No rule to make target `ChangeLog.md', needed by `all-am'.  Stop.
```

**Comment by troglobit** [comment]
Dammit, thanks for bringing this to my attention. I *knew* I should have double and triple checked ... :disappointed:

**Comment by abelbeck** [comment]
2.1.1 works perfectly, THANKS for your prompt fix.

**Comment by troglobit** [comment]
@abelbeck No problem, just embarrassing I didn't check myself first. Sorry about that :flushed: :smile:
