### ISSUE TITLE
Add support for validating IPv4/IPV6 address

### ISSUE THREAD

**Issue by abelbeck** [troglobit/netcalc#5]
First, great tool !  We had a request for sipcalc for our project, but your adaptation seems perfect.

Is it time to make 2.0.1 official ?

A minor point, the automatic symlink creation of ipcalc is unwanted in our case, we use the Busybox flavor ```/bin/ipcalc``` in scripts, so we had to skip your Makefile target install to eliminate ```/usr/bin/ipcalc``` confusion.

A suggestion, add options to validate IPv4/IPv6 addresses ...
```
-c  Validate the IPv4 address, returns non-zero on invalid address, no output
-C  Validate the IPv6 address, returns non-zero on invalid address, no output
```

Thank your for ```netcalc```.

**Comment by troglobit** [comment]
Thank you for the kind words!

Hmm, yeah I should probably invest some time in this project to add the few features I've been thinking about, and push out a new release.

Good idea, I'll look into adding a `configure --disable-ipcalc-symlink` option.

It's always a good idea to put separate feature requests into separate issues ... or do you have a pull-request for me waiting in the wings? :smirk:

**Comment by abelbeck** [comment]
No PR waiting in the wings, but you may hear from me again :-)

We currently use some obfuscated bash code to calculate dnsmasq DHCP lease ranges, if ```netcalc``` needs an option to make this more straightforward to calculate I'll be sure to share it.

**Comment by troglobit** [comment]
Merged, closing issue and starting to prepare next major release, v2.1.  I'll start by bumping to v2.1-beta1, in case you have any more pull requests lined up ;-)

Cheers

**Comment by abelbeck** [comment]
Sound good.
